"""update ticket model with status and event time

Revision ID: 357977d7194b
Revises: 1eae60229c15
Create Date: 2026-03-29 00:04:05.351608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '357977d7194b'
down_revision: Union[str, Sequence[str], None] = '1eae60229c15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('seller_id', sa.Integer(), nullable=False))
    op.add_column('tickets', sa.Column('status', sa.String(), nullable=False))
    op.add_column('tickets', sa.Column('event_date_time', sa.DateTime(), nullable=False))
    op.drop_constraint(op.f('tickets_owner_id_fkey'), 'tickets', type_='foreignkey')
    op.create_foreign_key(None, 'tickets', 'users', ['seller_id'], ['id'])
    op.drop_column('tickets', 'owner_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.create_foreign_key(op.f('tickets_owner_id_fkey'), 'tickets', 'users', ['owner_id'], ['id'])
    op.drop_column('tickets', 'event_date_time')
    op.drop_column('tickets', 'status')
    op.drop_column('tickets', 'seller_id')
    # ### end Alembic commands ###
